repos:
  # Basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Lint with ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: ["--fix"]

  # Format with black
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  # Sort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  # Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

  # Security scan
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-ll", "-r", "."]

  # Conventional commits (commit-msg hook)
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.6.3
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # # Optional: quick test check
  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: poetry run pytest --maxfail=1 --disable-warnings -q
  #       language: system
  #       types: [python]
